### PR TITLE
do not block other namespace-packages

### PR DESCRIPTION
**Pull request by looooo**
It's also possible to remove the freecad/__init__.py file but this works only with py3. Not sure if this workbench should also work with py2.

### CODE REVIEW

**Comment by looooo** [comment]
btw.: are you interested in making this workbench installable with pip? If you want I can have a look at this.

**Comment by realthunder** [comment]
> btw.: are you interested in making this workbench installable with pip? If you want I can have a look at this.

I am not sure. Since it is only workable in FreeCAD, I think add it to addon manager is enough?

It is the Solvespace python extension that I want to make it pip installable. You seem to have already prepackaged slvs in conda image. But there are still non-conda users. Maybe you can have a look [here](https://github.com/realthunder/slvs_py). Thanks!

**Comment by looooo** [comment]
> It is the Solvespace python extension that I want to make it pip installable. You seem to have already prepackaged slvs in conda image. But there are still non-conda users. Maybe you can have a look here. Thanks!

I have seen some topics about creating wheels from conda-recipes. Maybe that might be a solution for solvespace.

**Comment by looooo** [comment]
https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#output-type reminder for myself.

**Pull request merged**
