### PR TITLE
Add translation infrastructure to Assembly3

### LINKED ISSUE #142: Adding translation infrastructure to Assembly3
@realthunder is it too premature to implement the framework to have assembly3 translated to other languages? I'd be happy to help with this (as far as my technical know-how lets me)

Ref: https://forum.freecadweb.org/viewtopic.php?f=3&t=25180#p197884

### PR DESCRIPTION
**Pull request by luzpaz**
Closes #142

### CODE REVIEW

**Comment by realthunder** [comment]
Is this still 'work in progress', because I saw this earlier and it is marked as such.

**Comment by realthunder** [comment]
@luzpaz What's the difference between `FreeCAD.Qt.translate()` and `QT_TRANSLATE_NOOP()`? I see you import `FreeCAD.Qt.translate` but opt to use `QT_TRANSLATE_NOOP` somehow?

**Comment by luzpaz** [comment]
@realthunder it's explained in https://wiki.freecadweb.org/Translating_an_external_workbench#In_every_Python_.py_file

**Comment by kaktusus** [comment]
how the availability of translations looks like at the moment ?
Others have even prepared guides for translators
https://github.com/shaise/FreeCAD_SheetMetal/blob/master/TRANSLATIONS.md
https://github.com/shaise/FreeCAD_FastenersWB/blob/master/TRANSLATIONS.md

However, the most convenient solution is to add a workbench to FreeCAD-Addons on the Crowdin platform.
https://crowdin.com/project/freecad-addons/pl

**Pull request merged**
